# Generated by Django 4.2.23 on 2025-08-28 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refrigerant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام ماده مبرد')),
                ('coolprop_name', models.CharField(max_length=50, verbose_name='نام در CoolProp')),
            ],
            options={
                'verbose_name': 'ماده مبرد',
                'verbose_name_plural': 'مواد مبرد',
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محاسبه')),
                ('t_evap', models.FloatField(verbose_name='دمای اواپراتور (°C)')),
                ('t_cond', models.FloatField(verbose_name='دمای کندانسور (°C)')),
                ('mass_flow', models.FloatField(verbose_name='نرخ جرمی (kg/s)')),
                ('cop_ideal', models.FloatField(blank=True, null=True, verbose_name='COP ایده\u200cآل')),
                ('cop_actual', models.FloatField(blank=True, null=True, verbose_name='COP واقعی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('refrigerant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle_calculator.refrigerant', verbose_name='ماده مبرد')),
            ],
            options={
                'verbose_name': 'محاسبه',
                'verbose_name_plural': 'محاسبات',
                'ordering': ['-created_at'],
            },
        ),
    ]
